// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID       string     `json:"id"`
	PostID   string     `json:"postID"`
	ParentID *string    `json:"parentID,omitempty"`
	Content  string     `json:"content"`
	Children []*Comment `json:"children"`
}

type Mutation struct {
}

type Post struct {
	ID               string     `json:"id"`
	Title            string     `json:"title"`
	Content          string     `json:"content"`
	Comments         []*Comment `json:"comments"`
	CommentsDisabled bool       `json:"commentsDisabled"`
}

type Query struct {
}

type Subscription struct {
}
