name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Обновлено с v2 на v3

      - name: Set up Go
        uses: actions/setup-go@v4 # Обновлено с v2 на v4
        with:
          go-version: 1.20

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...
