on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Install dependencies
        run: go mod download


      - name: Run tests
        run: go test -v internal/graph/resolver_test.go


